### ISSUE TITLE
Plans for adding async/await support?

### ISSUE THREAD

**Issue by matteocontrini** [leypascua/ZeroNsq#7]
Hi, do you have plans for adding support for asynchronous methods?
For the publisher part, I think it wouldn't require much work, while for the subscriber I'm not sure...

I see that there are some `Thread.Sleep` calls around, and this really stops me from using this library. I need to run a NSQ subscriber in an ASP.NET application and I don't think blocking threads would be a good idea.

Thanks.

**Comment by leypascua** [comment]
@matteocontrini Plan is to move completely to async methods and just introduce extension methods for synchronous calls. 

Unfortunately, I haven't found the time to remove the Thread.Sleep calls but I will get back to it as soon as schedule permits. Thanks for taking a look :)

**Comment by leypascua** [comment]
See release [0.1.3.22b](https://github.com/leypascua/ZeroNsq/releases/tag/0.1.3.22)
